### ISSUE TITLE
Link error on Windows with Rust 1.33.0

### ISSUE THREAD

**Issue by askeksa** [saurvs/nfd-rs#14]
Thanks for this useful crate.

After upgrading Rust to 1.33.0 I get the following link error from `nfd` when building [Cinter](https://github.com/askeksa/Cinter):
```
libnfd-ec2bb1b08ec0519c.rlib(nfd_win.o) : error LNK2019: unresolved external symbol __imp_SHCreateItemFromParsingName referenced in function "enum nfdresult_t __cdecl SetDefaultPath(struct IFileDialog *,char const *)" (?SetDefaultPath@@YA?AW4nfdresult_t@@PEAUIFileDialog@@PEBD@Z)
```
1.32.0 works fine.

I'm on Windows 10 with Visual Studio 2017.

**Comment by bzm3r** [comment]
I am having the same issue!
