### PR TITLE
Add shell32 library

### LINKED ISSUE #14: Link error on Windows with Rust 1.33.0
Thanks for this useful crate.

After upgrading Rust to 1.33.0 I get the following link error from `nfd` when building [Cinter](https://github.com/askeksa/Cinter):
```
libnfd-ec2bb1b08ec0519c.rlib(nfd_win.o) : error LNK2019: unresolved external symbol __imp_SHCreateItemFromParsingName referenced in function "enum nfdresult_t __cdecl SetDefaultPath(struct IFileDialog *,char const *)" (?SetDefaultPath@@YA?AW4nfdresult_t@@PEAUIFileDialog@@PEBD@Z)
```
1.32.0 works fine.

I'm on Windows 10 with Visual Studio 2017.

### PR DESCRIPTION
**Pull request by raphlinus**
This was included by default for older Rust versions but is now needed explicitly as of 1.33.0.

Fixes #14

### CODE REVIEW

**Comment by raphlinus** [comment]
See the [Reddit thread](https://www.reddit.com/r/rust/comments/avuwj3/announcing_rust_1330/ehi1gdb/) on the 1.33 release for more info about why this is necessary.

**Comment by saurvs** [comment]
@raphlinus thanks, merging
